from __future__ import annotations

from typing import Any


REPO_NOT_SUPPORTED = "REPO_NOT_SUPPORTED"
REPO_PROFILE_INVALID = "REPO_PROFILE_INVALID"
HARNESS_NOT_SUPPORTED = "HARNESS_NOT_SUPPORTED"
CAPABILITY_NOT_FOUND = "CAPABILITY_NOT_FOUND"
CAPABILITY_DEPENDENCY_MISSING = "CAPABILITY_DEPENDENCY_MISSING"
CAPABILITY_OWNERSHIP_CONFLICT = "CAPABILITY_OWNERSHIP_CONFLICT"
UPSTREAM_SOURCE_UNRESOLVED = "UPSTREAM_SOURCE_UNRESOLVED"
UPSTREAM_SHA_NOT_PINNED = "UPSTREAM_SHA_NOT_PINNED"
SPEC_KIT_RECONCILE_CONFLICT = "SPEC_KIT_RECONCILE_CONFLICT"
SPEC_KIT_MANAGED_CONFLICT = "SPEC_KIT_MANAGED_CONFLICT"
SPEC_KIT_RUNTIME_INCOMPLETE = "SPEC_KIT_RUNTIME_INCOMPLETE"
SPEC_KIT_RENDER_FAILED = "SPEC_KIT_RENDER_FAILED"
SPEC_KIT_UNRESOLVED_TOKEN = "SPEC_KIT_UNRESOLVED_TOKEN"
MANAGED_CONTENT_MODIFIED = "MANAGED_CONTENT_MODIFIED"
BUSINESS_SOURCE_MODIFICATION_FORBIDDEN = "BUSINESS_SOURCE_MODIFICATION_FORBIDDEN"
LEGACY_OWNERSHIP_UNKNOWN = "LEGACY_OWNERSHIP_UNKNOWN"
GES_RECONCILE_NOOP = "GES_RECONCILE_NOOP"
GES_CHECK_FAILED = "GES_CHECK_FAILED"
GES_CHECK_PASS = "GES_CHECK_PASS"
SPEC_SEMANTIC_GAP = "SPEC_SEMANTIC_GAP"
SPEC_NOT_IMPLEMENTABLE = "SPEC_NOT_IMPLEMENTABLE"
DESIRED_STATE_INVALID = "DESIRED_STATE_INVALID"
PROJECTION_PATH_CONFLICT = "PROJECTION_PATH_CONFLICT"
SOURCE_CACHE_INTEGRITY_FAILED = "SOURCE_CACHE_INTEGRITY_FAILED"
TRANSACTION_ROLLBACK_FAILED = "TRANSACTION_ROLLBACK_FAILED"
EVIDENCE_MISSING = "EVIDENCE_MISSING"
UNMANAGED_PATH_CONFLICT = "UNMANAGED_PATH_CONFLICT"
BOOTSTRAP_PREREQUISITE_FAILED = "BOOTSTRAP_PREREQUISITE_FAILED"
RECONFIGURE_NOT_SUPPORTED = "RECONFIGURE_NOT_SUPPORTED"

ERROR_CODES = (
    REPO_NOT_SUPPORTED,
    REPO_PROFILE_INVALID,
    HARNESS_NOT_SUPPORTED,
    CAPABILITY_NOT_FOUND,
    CAPABILITY_DEPENDENCY_MISSING,
    CAPABILITY_OWNERSHIP_CONFLICT,
    UPSTREAM_SOURCE_UNRESOLVED,
    UPSTREAM_SHA_NOT_PINNED,
    SPEC_KIT_RECONCILE_CONFLICT,
    SPEC_KIT_MANAGED_CONFLICT,
    SPEC_KIT_RUNTIME_INCOMPLETE,
    SPEC_KIT_RENDER_FAILED,
    SPEC_KIT_UNRESOLVED_TOKEN,
    MANAGED_CONTENT_MODIFIED,
    BUSINESS_SOURCE_MODIFICATION_FORBIDDEN,
    LEGACY_OWNERSHIP_UNKNOWN,
    GES_RECONCILE_NOOP,
    GES_CHECK_FAILED,
    GES_CHECK_PASS,
    SPEC_SEMANTIC_GAP,
    SPEC_NOT_IMPLEMENTABLE,
    DESIRED_STATE_INVALID,
    PROJECTION_PATH_CONFLICT,
    SOURCE_CACHE_INTEGRITY_FAILED,
    TRANSACTION_ROLLBACK_FAILED,
    EVIDENCE_MISSING,
    UNMANAGED_PATH_CONFLICT,
    BOOTSTRAP_PREREQUISITE_FAILED,
    RECONFIGURE_NOT_SUPPORTED,
)


class GesError(Exception):
    """Typed GES Composer failure with a frozen PRD error code."""

    def __init__(self, code: str, message: str, *, details: dict[str, Any] | None = None):
        if code not in ERROR_CODES:
            raise ValueError(f"unknown GES error code: {code}")
        self.code = code
        self.message = message
        self.details = details or {}
        super().__init__(f"{code}: {message}")
