from __future__ import annotations

from typing import Any


REPO_NOT_SUPPORTED = "REPO_NOT_SUPPORTED"
REPO_PROFILE_INVALID = "REPO_PROFILE_INVALID"
HARNESS_NOT_SUPPORTED = "HARNESS_NOT_SUPPORTED"
CAPABILITY_NOT_FOUND = "CAPABILITY_NOT_FOUND"
CAPABILITY_DEPENDENCY_MISSING = "CAPABILITY_DEPENDENCY_MISSING"
CAPABILITY_OWNERSHIP_CONFLICT = "CAPABILITY_OWNERSHIP_CONFLICT"
UPSTREAM_SOURCE_UNRESOLVED = "UPSTREAM_SOURCE_UNRESOLVED"
UPSTREAM_SHA_NOT_PINNED = "UPSTREAM_SHA_NOT_PINNED"
SPEC_KIT_RECONCILE_CONFLICT = "SPEC_KIT_RECONCILE_CONFLICT"
SPEC_KIT_MANAGED_CONFLICT = "SPEC_KIT_MANAGED_CONFLICT"
SPEC_KIT_RUNTIME_INCOMPLETE = "SPEC_KIT_RUNTIME_INCOMPLETE"
SPEC_KIT_RENDER_FAILED = "SPEC_KIT_RENDER_FAILED"
SPEC_KIT_UNRESOLVED_TOKEN = "SPEC_KIT_UNRESOLVED_TOKEN"
MANAGED_CONTENT_MODIFIED = "MANAGED_CONTENT_MODIFIED"
BUSINESS_SOURCE_MODIFICATION_FORBIDDEN = "BUSINESS_SOURCE_MODIFICATION_FORBIDDEN"
LEGACY_OWNERSHIP_UNKNOWN = "LEGACY_OWNERSHIP_UNKNOWN"
GES_RECONCILE_NOOP = "GES_RECONCILE_NOOP"
GES_CHECK_FAILED = "GES_CHECK_FAILED"
GES_CHECK_PASS = "GES_CHECK_PASS"
SPEC_SEMANTIC_GAP = "SPEC_SEMANTIC_GAP"
SPEC_NOT_IMPLEMENTABLE = "SPEC_NOT_IMPLEMENTABLE"
DESIRED_STATE_INVALID = "DESIRED_STATE_INVALID"
PROJECTION_PATH_CONFLICT = "PROJECTION_PATH_CONFLICT"
SOURCE_CACHE_INTEGRITY_FAILED = "SOURCE_CACHE_INTEGRITY_FAILED"
TRANSACTION_ROLLBACK_FAILED = "TRANSACTION_ROLLBACK_FAILED"
EVIDENCE_MISSING = "EVIDENCE_MISSING"
UNMANAGED_PATH_CONFLICT = "UNMANAGED_PATH_CONFLICT"
BOOTSTRAP_PREREQUISITE_FAILED = "BOOTSTRAP_PREREQUISITE_FAILED"
RECONFIGURE_NOT_SUPPORTED = "RECONFIGURE_NOT_SUPPORTED"
SPEC_KIT_OFFICIAL_RENDER_FAILED = "SPEC_KIT_OFFICIAL_RENDER_FAILED"
SPEC_KIT_CLI_IDENTITY_MISMATCH = "SPEC_KIT_CLI_IDENTITY_MISMATCH"
CURSOR_CLI_NOT_FOUND = "CURSOR_CLI_NOT_FOUND"
CURSOR_RUNTIME_UNAVAILABLE = "CURSOR_RUNTIME_UNAVAILABLE"
CURSOR_DISCOVERY_FAILED = "CURSOR_DISCOVERY_FAILED"
CURSOR_DISCOVERY_OUTPUT_INVALID = "CURSOR_DISCOVERY_OUTPUT_INVALID"
SPEC_KIT_FUNCTIONAL_SMOKE_FAILED = "SPEC_KIT_FUNCTIONAL_SMOKE_FAILED"
GOLDEN_CONSUMER_HEAD_UNRESOLVED = "GOLDEN_CONSUMER_HEAD_UNRESOLVED"
GOLDEN_UNEXPECTED_MUTATION = "GOLDEN_UNEXPECTED_MUTATION"
GES_IDEMPOTENCY_FAILED = "GES_IDEMPOTENCY_FAILED"
STALE_EVIDENCE = "STALE_EVIDENCE"
EVIDENCE_COMMIT_MISMATCH = "EVIDENCE_COMMIT_MISMATCH"
EVIDENCE_CANDIDATE_MOVED = "EVIDENCE_CANDIDATE_MOVED"
EVIDENCE_ARTIFACT_MISSING = "EVIDENCE_ARTIFACT_MISSING"
SPEC_KIT_SMOKE_SPEC_MISSING = "SPEC_KIT_SMOKE_SPEC_MISSING"
SPEC_KIT_SMOKE_FEATURE_STATE_MISSING = "SPEC_KIT_SMOKE_FEATURE_STATE_MISSING"
SPEC_KIT_SMOKE_FEATURE_STATE_INVALID = "SPEC_KIT_SMOKE_FEATURE_STATE_INVALID"
ACCEPTANCE_OBSERVER_MUTATED_SUT = "ACCEPTANCE_OBSERVER_MUTATED_SUT"
CURSOR_NATIVE_DISCOVERY_FAILED = "CURSOR_NATIVE_DISCOVERY_FAILED"
CURSOR_SKILL_METADATA_MISMATCH = "CURSOR_SKILL_METADATA_MISMATCH"
RELEASE_CANDIDATE_SYNTHETIC_FAILED = "RELEASE_CANDIDATE_SYNTHETIC_FAILED"
GOLDEN_RELEASE_GATE_FAILED = "GOLDEN_RELEASE_GATE_FAILED"
RELEASE_DOCUMENTATION_STALE = "RELEASE_DOCUMENTATION_STALE"
RELEASE_TAG_COMMIT_MISMATCH = "RELEASE_TAG_COMMIT_MISMATCH"
GOVERNANCE_ALREADY_INITIALIZED = "GOVERNANCE_ALREADY_INITIALIZED"
GOVERNANCE_PATH_CONFLICT = "GOVERNANCE_PATH_CONFLICT"
GOVERNANCE_NOT_INITIALIZED = "GOVERNANCE_NOT_INITIALIZED"
WORK_ALREADY_EXISTS = "WORK_ALREADY_EXISTS"
WORK_NOT_FOUND = "WORK_NOT_FOUND"
WORK_ID_INVALID = "WORK_ID_INVALID"
WORK_STATE_TRANSITION_INVALID = "WORK_STATE_TRANSITION_INVALID"
WORK_CLOSED_IMMUTABLE = "WORK_CLOSED_IMMUTABLE"
ARTIFACT_ALREADY_BOUND = "ARTIFACT_ALREADY_BOUND"
ARTIFACT_STALE = "ARTIFACT_STALE"
ARTIFACT_PATH_INVALID = "ARTIFACT_PATH_INVALID"
ARTIFACT_PATH_UNSAFE = "ARTIFACT_PATH_UNSAFE"
REQUIRED_ARTIFACT_MISSING = "REQUIRED_ARTIFACT_MISSING"
POLICY_SCHEMA_INVALID = "POLICY_SCHEMA_INVALID"
GITHUB_PROVIDER_UNAVAILABLE = "GITHUB_PROVIDER_UNAVAILABLE"
GITHUB_AUTH_UNAVAILABLE = "GITHUB_AUTH_UNAVAILABLE"
GITHUB_PROVIDER_INVALID = "GITHUB_PROVIDER_INVALID"
PR_WORK_BINDING_MISSING = "PR_WORK_BINDING_MISSING"
PR_WORK_BINDING_CONFLICT = "PR_WORK_BINDING_CONFLICT"
PR_HEAD_MISMATCH = "PR_HEAD_MISMATCH"
EVIDENCE_SUBJECT_MISMATCH = "EVIDENCE_SUBJECT_MISMATCH"
REVIEW_REQUIRED = "REVIEW_REQUIRED"
CI_CHECK_PENDING = "CI_CHECK_PENDING"
APPROVAL_REQUIRED_UNSUPPORTED = "APPROVAL_REQUIRED_UNSUPPORTED"
PR_HEAD_CHANGED_DURING_EVALUATION = "PR_HEAD_CHANGED_DURING_EVALUATION"
LOCAL_HEAD_CHANGED_DURING_EVALUATION = "LOCAL_HEAD_CHANGED_DURING_EVALUATION"
WORKTREE_DIRTY = "WORKTREE_DIRTY"
UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"

ERROR_CODES = (
    REPO_NOT_SUPPORTED,
    REPO_PROFILE_INVALID,
    HARNESS_NOT_SUPPORTED,
    CAPABILITY_NOT_FOUND,
    CAPABILITY_DEPENDENCY_MISSING,
    CAPABILITY_OWNERSHIP_CONFLICT,
    UPSTREAM_SOURCE_UNRESOLVED,
    UPSTREAM_SHA_NOT_PINNED,
    SPEC_KIT_RECONCILE_CONFLICT,
    SPEC_KIT_MANAGED_CONFLICT,
    SPEC_KIT_RUNTIME_INCOMPLETE,
    SPEC_KIT_RENDER_FAILED,
    SPEC_KIT_UNRESOLVED_TOKEN,
    MANAGED_CONTENT_MODIFIED,
    BUSINESS_SOURCE_MODIFICATION_FORBIDDEN,
    LEGACY_OWNERSHIP_UNKNOWN,
    GES_RECONCILE_NOOP,
    GES_CHECK_FAILED,
    GES_CHECK_PASS,
    SPEC_SEMANTIC_GAP,
    SPEC_NOT_IMPLEMENTABLE,
    DESIRED_STATE_INVALID,
    PROJECTION_PATH_CONFLICT,
    SOURCE_CACHE_INTEGRITY_FAILED,
    TRANSACTION_ROLLBACK_FAILED,
    EVIDENCE_MISSING,
    UNMANAGED_PATH_CONFLICT,
    BOOTSTRAP_PREREQUISITE_FAILED,
    RECONFIGURE_NOT_SUPPORTED,
    SPEC_KIT_OFFICIAL_RENDER_FAILED,
    SPEC_KIT_CLI_IDENTITY_MISMATCH,
    CURSOR_CLI_NOT_FOUND,
    CURSOR_RUNTIME_UNAVAILABLE,
    CURSOR_DISCOVERY_FAILED,
    CURSOR_DISCOVERY_OUTPUT_INVALID,
    SPEC_KIT_FUNCTIONAL_SMOKE_FAILED,
    GOLDEN_CONSUMER_HEAD_UNRESOLVED,
    GOLDEN_UNEXPECTED_MUTATION,
    GES_IDEMPOTENCY_FAILED,
    STALE_EVIDENCE,
    EVIDENCE_COMMIT_MISMATCH,
    EVIDENCE_CANDIDATE_MOVED,
    EVIDENCE_ARTIFACT_MISSING,
    SPEC_KIT_SMOKE_SPEC_MISSING,
    SPEC_KIT_SMOKE_FEATURE_STATE_MISSING,
    SPEC_KIT_SMOKE_FEATURE_STATE_INVALID,
    ACCEPTANCE_OBSERVER_MUTATED_SUT,
    CURSOR_NATIVE_DISCOVERY_FAILED,
    CURSOR_SKILL_METADATA_MISMATCH,
    RELEASE_CANDIDATE_SYNTHETIC_FAILED,
    GOLDEN_RELEASE_GATE_FAILED,
    RELEASE_DOCUMENTATION_STALE,
    RELEASE_TAG_COMMIT_MISMATCH,
    GOVERNANCE_ALREADY_INITIALIZED,
    GOVERNANCE_PATH_CONFLICT,
    GOVERNANCE_NOT_INITIALIZED,
    WORK_ALREADY_EXISTS,
    WORK_NOT_FOUND,
    WORK_ID_INVALID,
    WORK_STATE_TRANSITION_INVALID,
    WORK_CLOSED_IMMUTABLE,
    ARTIFACT_ALREADY_BOUND,
    ARTIFACT_STALE,
    ARTIFACT_PATH_INVALID,
    ARTIFACT_PATH_UNSAFE,
    REQUIRED_ARTIFACT_MISSING,
    POLICY_SCHEMA_INVALID,
    GITHUB_PROVIDER_UNAVAILABLE,
    GITHUB_AUTH_UNAVAILABLE,
    GITHUB_PROVIDER_INVALID,
    PR_WORK_BINDING_MISSING,
    PR_WORK_BINDING_CONFLICT,
    PR_HEAD_MISMATCH,
    EVIDENCE_SUBJECT_MISMATCH,
    REVIEW_REQUIRED,
    CI_CHECK_PENDING,
    APPROVAL_REQUIRED_UNSUPPORTED,
    PR_HEAD_CHANGED_DURING_EVALUATION,
    LOCAL_HEAD_CHANGED_DURING_EVALUATION,
    WORKTREE_DIRTY,
    UNSUPPORTED_OPERATION,
)


class GesError(Exception):
    """Typed GES Composer failure with a frozen PRD error code."""

    def __init__(
        self,
        code: str,
        message: str,
        *,
        details: dict[str, Any] | None = None,
        exit_code: int = 2,
    ):
        if code not in ERROR_CODES:
            raise ValueError(f"unknown GES error code: {code}")
        self.code = code
        self.message = message
        self.details = details or {}
        self.exit_code = exit_code
        super().__init__(f"{code}: {message}")
