from __future__ import annotations

from typing import Any


REPO_NOT_SUPPORTED = "REPO_NOT_SUPPORTED"
REPO_PROFILE_INVALID = "REPO_PROFILE_INVALID"
HARNESS_NOT_SUPPORTED = "HARNESS_NOT_SUPPORTED"
CAPABILITY_NOT_FOUND = "CAPABILITY_NOT_FOUND"
CAPABILITY_DEPENDENCY_MISSING = "CAPABILITY_DEPENDENCY_MISSING"
CAPABILITY_OWNERSHIP_CONFLICT = "CAPABILITY_OWNERSHIP_CONFLICT"
UPSTREAM_SOURCE_UNRESOLVED = "UPSTREAM_SOURCE_UNRESOLVED"
UPSTREAM_SHA_NOT_PINNED = "UPSTREAM_SHA_NOT_PINNED"
SPEC_KIT_RECONCILE_CONFLICT = "SPEC_KIT_RECONCILE_CONFLICT"
MANAGED_CONTENT_MODIFIED = "MANAGED_CONTENT_MODIFIED"
BUSINESS_SOURCE_MODIFICATION_FORBIDDEN = "BUSINESS_SOURCE_MODIFICATION_FORBIDDEN"
LEGACY_OWNERSHIP_UNKNOWN = "LEGACY_OWNERSHIP_UNKNOWN"
GES_RECONCILE_NOOP = "GES_RECONCILE_NOOP"
GES_CHECK_FAILED = "GES_CHECK_FAILED"
GES_CHECK_PASS = "GES_CHECK_PASS"

ERROR_CODES = (
    REPO_NOT_SUPPORTED,
    REPO_PROFILE_INVALID,
    HARNESS_NOT_SUPPORTED,
    CAPABILITY_NOT_FOUND,
    CAPABILITY_DEPENDENCY_MISSING,
    CAPABILITY_OWNERSHIP_CONFLICT,
    UPSTREAM_SOURCE_UNRESOLVED,
    UPSTREAM_SHA_NOT_PINNED,
    SPEC_KIT_RECONCILE_CONFLICT,
    MANAGED_CONTENT_MODIFIED,
    BUSINESS_SOURCE_MODIFICATION_FORBIDDEN,
    LEGACY_OWNERSHIP_UNKNOWN,
    GES_RECONCILE_NOOP,
    GES_CHECK_FAILED,
    GES_CHECK_PASS,
)


class GesError(Exception):
    """Typed GES Composer failure with a frozen PRD error code."""

    def __init__(self, code: str, message: str, *, details: dict[str, Any] | None = None):
        if code not in ERROR_CODES:
            raise ValueError(f"unknown GES error code: {code}")
        self.code = code
        self.message = message
        self.details = details or {}
        super().__init__(f"{code}: {message}")
