from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from typing import Any, TextIO

PREFLIGHT = "PREFLIGHT"
ANALYZE = "ANALYZE"
RESOLVE = "RESOLVE"
FETCH = "FETCH"
RENDER = "RENDER"
PROJECT = "PROJECT"
COLLISION_CHECK = "COLLISION_CHECK"
PLAN = "PLAN"
APPLY = "APPLY"
RECONCILE = "RECONCILE"
CHECK = "CHECK"
DOCTOR = "DOCTOR"
REMOVE = "REMOVE"
SPECKIT_CLI_VERIFY = "SPECKIT_CLI_VERIFY"
SPECKIT_OFFICIAL_RENDER = "SPECKIT_OFFICIAL_RENDER"
SPECKIT_MANIFEST_COMPARE = "SPECKIT_MANIFEST_COMPARE"
GOLDEN_RESOLVE = "GOLDEN_RESOLVE"
GOLDEN_WORKTREE_CREATE = "GOLDEN_WORKTREE_CREATE"
GES_PREFLIGHT = "GES_PREFLIGHT"
GES_INIT = "GES_INIT"
GES_CHECK = "GES_CHECK"
GES_DOCTOR = "GES_DOCTOR"
CURSOR_STRUCTURAL_DISCOVERY = "CURSOR_STRUCTURAL_DISCOVERY"
CURSOR_RUNTIME_DISCOVERY = "CURSOR_RUNTIME_DISCOVERY"
SPECKIT_FUNCTIONAL_SMOKE = "SPECKIT_FUNCTIONAL_SMOKE"
GES_SECOND_INIT = "GES_SECOND_INIT"
EVIDENCE_WRITE = "EVIDENCE_WRITE"
GOLDEN_WORKTREE_CLEANUP = "GOLDEN_WORKTREE_CLEANUP"
RELEASE_GATE = "RELEASE_GATE"
RC_FREEZE = "RC_FREEZE"
SYNTHETIC_CI = "SYNTHETIC_CI"
GOLDEN_CI = "GOLDEN_CI"
CURSOR_NATIVE_DISCOVERY = "CURSOR_NATIVE_DISCOVERY"
SPECKIT_STRICT_SMOKE = "SPECKIT_STRICT_SMOKE"
EVIDENCE_BIND = "EVIDENCE_BIND"
DOC_STATUS_CHECK = "DOC_STATUS_CHECK"
TAG_VERIFY = "TAG_VERIFY"
RELEASE_ASSET = "RELEASE_ASSET"
GOVERNANCE_INIT = "GOVERNANCE_INIT"
WORK_LOAD = "WORK_LOAD"
WORK_VALIDATE = "WORK_VALIDATE"
ARTIFACT_RESOLVE = "ARTIFACT_RESOLVE"
POLICY_LOAD = "POLICY_LOAD"
GIT_OBSERVE = "GIT_OBSERVE"
GITHUB_OBSERVE = "GITHUB_OBSERVE"
EVIDENCE_RESOLVE = "EVIDENCE_RESOLVE"
TRACE_BUILD = "TRACE_BUILD"
GATE_INTAKE = "GATE_INTAKE"
GATE_MERGE = "GATE_MERGE"
GATE_EXPLAIN = "GATE_EXPLAIN"

STAGES = (
    PREFLIGHT,
    ANALYZE,
    RESOLVE,
    FETCH,
    RENDER,
    PROJECT,
    COLLISION_CHECK,
    PLAN,
    APPLY,
    RECONCILE,
    CHECK,
    DOCTOR,
    REMOVE,
    SPECKIT_CLI_VERIFY,
    SPECKIT_OFFICIAL_RENDER,
    SPECKIT_MANIFEST_COMPARE,
    GOLDEN_RESOLVE,
    GOLDEN_WORKTREE_CREATE,
    GES_PREFLIGHT,
    GES_INIT,
    GES_CHECK,
    GES_DOCTOR,
    CURSOR_STRUCTURAL_DISCOVERY,
    CURSOR_RUNTIME_DISCOVERY,
    SPECKIT_FUNCTIONAL_SMOKE,
    GES_SECOND_INIT,
    EVIDENCE_WRITE,
    GOLDEN_WORKTREE_CLEANUP,
    RELEASE_GATE,
    RC_FREEZE,
    SYNTHETIC_CI,
    GOLDEN_CI,
    CURSOR_NATIVE_DISCOVERY,
    SPECKIT_STRICT_SMOKE,
    EVIDENCE_BIND,
    DOC_STATUS_CHECK,
    TAG_VERIFY,
    RELEASE_ASSET,
    GOVERNANCE_INIT,
    WORK_LOAD,
    WORK_VALIDATE,
    ARTIFACT_RESOLVE,
    POLICY_LOAD,
    GIT_OBSERVE,
    GITHUB_OBSERVE,
    EVIDENCE_RESOLVE,
    TRACE_BUILD,
    GATE_INTAKE,
    GATE_MERGE,
    GATE_EXPLAIN,
)


def emit(stage: str, event: str, **fields: Any) -> None:
    """Emit one structured Composer operation log line. No LLM telemetry."""
    if stage not in STAGES:
        raise ValueError(f"unknown stage: {stage}")
    record = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "stage": stage,
        "event": event,
        **fields,
    }
    _write(sys.stderr, record)


def _write(stream: TextIO, record: dict[str, Any]) -> None:
    stream.write(json.dumps(record, ensure_ascii=False, default=str) + "\n")
    stream.flush()
